# Inspired from https://github.com/openshift/cluster-openshift-controller-manager-operator/blob/master/.ci-operator.yaml
build_root_image:
  namespace: openshift
  name: release
  tag: rhel-9-release-golang-1.25-openshift-4.21 
