version: "2"
run:
  go: "1.23"
linters:
  enable:
    - copyloopvar
    - cyclop
    - errcheck
    - errname
    - errorlint
    - exhaustive
    - gocritic
    - govet
    - ineffassign
    - revive
    - staticcheck
    - unused
  settings:
    cyclop:
      max-complexity: 20
    gocritic:
      enabled-checks:
        - hugeParam
        - rangeExprCopy
        - rangeValCopy
        - indexAlloc
      settings:
        ifElseChain:
          minThreshold: 3
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
    rules:
      - linters:
        - staticcheck
        text: "QF1003:"
      - linters:
        - staticcheck
        text: "QF1008:"
formatters:
  enable:
    - gofmt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
