apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# Adds namespace to all resources.
namespace: openshift-netobserv-operator

resources:
- ../common

patches:
  - path: ./tls-servername-patch.yaml
    target:
      kind: ServiceMonitor
      name: metrics-monitor
