kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: lockdown-netobserv
  namespace: netobserv
spec:
  podSelector: {}
  ingress:
    - from:
        - podSelector: {}  # without namespaceSelecor, it defaults to 'same namespace'
        - podSelector: {}
          namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: openshift-console
        - podSelector: {}
          namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: openshift-monitoring
  policyTypes:
    - Ingress
status: {}
