apiVersion: flows.netobserv.io/v1alpha1
kind: FlowMetric
metadata:
  name: flowmetric-pod-outgoing
spec:
  metricName: pod_outgoing_bytes_total
  type: Counter
  valueField: Bytes
  direction: Egress
  labels: [SrcK8S_Name,SrcK8S_Namespace,SrcK8S_OwnerName,SrcK8S_OwnerType,SrcK8S_HostName]
  filters:
  - field: SrcK8S_Type
    value: Pod
