apiVersion: flows.netobserv.io/v1alpha1
kind: FlowMetric
metadata:
  name: flowmetric-service-incoming
spec:
  metricName: service_incoming_bytes_total
  type: Counter
  valueField: Bytes
  # Note that we need to look from the sender point of view to get traffic to services, hence Egress here
  direction: Egress
  labels: [DstK8S_Name,DstK8S_Namespace,DstK8S_OwnerName,DstK8S_OwnerType,DstK8S_HostName]
  filters:
  - field: DstK8S_Type
    value: Service
