# Adds namespace to all resources.
namespace: openshift-netobserv-operator

# Value of this field is prepended to the
# names of all resources, e.g. a deployment named
# "wordpress" becomes "alices-wordpress".
# Note that it should also match with the prefix (text before '-') of the namespace
# field above.
namePrefix: netobserv-

resources:
- monitor.yaml

patches:
  - path: ./monitoring-patch.yaml
    target:
      kind: Deployment
      name: controller-manager
# Labels to add to all resources and selectors.
#commonLabels:
#  someName: someValue

bases:
- ../crd
- ../rbac
- ../manager
- ../webhook
patchesStrategicMerge:
- patch.yaml
