package e2etests

import (
	"context"
	"fmt"
	"reflect"
	"strings"

	g "github.com/onsi/ginkgo/v2"
	o "github.com/onsi/gomega"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
)

// lokiStack contains the configurations of loki stack
type lokiStack struct {
	Name          string // lokiStack name
	Namespace     string // lokiStack namespace
	TSize         string // size
	StorageType   string // the backend storage type, currently support s3, gcs, azure, swift, ODF and minIO
	StorageSecret string // the secret name for loki to use to connect to backend storage
	StorageClass  string // storage class name
	BucketName    string // the butcket or the container name where loki stores it's data in
	Tenant        string // Loki tenant name
	Template      string // the file used to create the loki stack
	Route         string // lokistack-gateway-http route to be initialized after lokistack is up.
	EnableIPV6    string // enable IPV6
}

// LokiPersistentVolumeClaim struct to handle Loki PVC resources
type LokiPersistentVolumeClaim struct {
	Namespace string
	Template  string
}

// LokiStorage struct to handle LokiStorage resources
type LokiStorage struct {
	Namespace string
	Template  string
}

// DeployLokiStack creates the lokiStack CR with basic settings: name, namespace, size, storage.secret.name, storage.secret.type, storageClassName
// optionalParameters is designed for adding parameters to deploy lokiStack with different tenants or some other settings
func (l lokiStack) deployLokiStack() error {
	parameters := []string{"--ignore-unknown-parameters=true", "-f", l.Template, "-p"}

	lokistack := reflect.ValueOf(&l).Elem()

	for i := 0; i < lokistack.NumField(); i++ {
		if lokistack.Field(i).Interface() != "" {
			if lokistack.Type().Field(i).Name == "StorageType" {
				if lokistack.Field(i).Interface() == "odf" || lokistack.Field(i).Interface() == "minio" {
					parameters = append(parameters, fmt.Sprintf("%s=%s", lokistack.Type().Field(i).Name, "s3"))
				} else {
					parameters = append(parameters, fmt.Sprintf("%s=%s", lokistack.Type().Field(i).Name, lokistack.Field(i).Interface()))
				}
			} else {
				if lokistack.Type().Field(i).Name == "Template" {
					continue
				} else {
					parameters = append(parameters, fmt.Sprintf("%s=%s", lokistack.Type().Field(i).Name, lokistack.Field(i).Interface()))
				}
			}
		}
	}

	err := applyNsResourceFromTemplateByAdmin(l.Namespace, parameters...)
	o.Expect(err).NotTo(o.HaveOccurred(), fmt.Sprintf("Can not process %v", parameters))
	return err
}

func (l lokiStack) waitForLokiStackToBeReady() error {
	for _, deploy := range []string{l.Name + "-distributor", l.Name + "-gateway", l.Name + "-querier", l.Name + "-query-frontend"} {
		if err := waitForDeploymentPodsToBeReady(l.Namespace, deploy); err != nil {
			return err
		}
	}
	for _, ss := range []string{l.Name + "-compactor", l.Name + "-index-gateway", l.Name + "-ingester"} {
		if err := waitForStatefulsetReady(l.Namespace, ss); err != nil {
			return err
		}
	}
	if isWorkloadIdentityCluster() {
		currentPlatform := checkPlatform()
		switch currentPlatform {
		case "aws", "azure", "gcp":
			validateCredentialsRequestGenerationOnSTS(l.Name, l.Namespace)
		}
	}
	return nil
}

// To check CredentialsRequest is generated by Loki Operator on STS clusters for CCO flow
func validateCredentialsRequestGenerationOnSTS(lokiStackName, lokiNamespace string) {
	g.By("Validate that Loki Operator creates a CredentialsRequest object")
	obj, err := getDynamicResource("CredentialsRequest", lokiStackName, lokiNamespace)
	o.Expect(err).NotTo(o.HaveOccurred())

	cloudTokenPath, found := getNestedField(obj.Object, ".spec.cloudTokenPath")
	o.Expect(found).To(o.BeTrue())
	o.Expect(cloudTokenPath).Should(o.Equal("/var/run/secrets/storage/serviceaccount/token"))

	serviceAccountNames, saFound, _ := unstructured.NestedStringSlice(obj.Object, "spec", "serviceAccountNames")
	o.Expect(saFound).To(o.BeTrue())
	o.Expect(serviceAccountNames).Should(o.Equal([]string{lokiStackName, lokiStackName + "-ruler"}))
}

func (l lokiStack) removeLokiStack() {
	_ = Resource{"lokistack", l.Name, l.Namespace}.clear()
	_ = k8sClient.CoreV1().PersistentVolumeClaims(l.Namespace).DeleteCollection(
		context.Background(),
		metav1.DeleteOptions{},
		metav1.ListOptions{LabelSelector: "app.kubernetes.io/instance=" + l.Name},
	)
}

// Get OIDC provider for the cluster
func getOIDC() (string, error) {
	obj, err := getDynamicResource("authentication.config", "cluster", "")
	if err != nil {
		return "", err
	}
	oidc, _ := getNestedField(obj.Object, ".spec.serviceAccountIssuer")
	return strings.TrimPrefix(oidc, "https://"), nil
}

func isWorkloadIdentityCluster() bool {
	oidc, err := getOIDC()
	if err != nil {
		return false
	}
	return len(oidc) > 0
}
