apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  name: netobserv-1-9-3-fbc-4-18-0
  namespace: ocp-network-observab-tenant
  labels:
    release.appstudio.openshift.io/author: 'ocazade'
spec:
  releasePlan: netobserv-fbc-v4-18
  snapshot: catalog-4-18-5f4gl
