# This cluster role is installed but unused by default
# It is provided for operator being able to watch & copy a secret over namespaces,
# e.g. when using Kafka with TLS, installed in a different namespace
# To avoid cluster-wide access to secrets, it should be used with a RoleBinding (not ClusterRoleBinding).
# E.g:
# kubectl create rolebinding secret-watcher -n kafka-namespace --clusterrole=netobserv-secret-watcher --serviceaccount=netobserv:netobserv-controller-manager
# kubectl create rolebinding secret-creator -n netobserv --clusterrole=netobserv-secret-creator --serviceaccount=netobserv:netobserv-controller-manager
# kubectl create rolebinding secret-creator -n netobserv-privileged --clusterrole=netobserv-secret-creator --serviceaccount=netobserv:netobserv-controller-manager
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secret-watcher
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secret-creator
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
