spec:
  description: |-
    Defines the desired state of the FlowCollector resource.
    <br><br>
    *: the mention of "unsupported" or "deprecated" for a feature throughout this document means that this feature
    is not officially supported by Red Hat. It might have been, for example, contributed by the community
    and accepted without a formal agreement for maintenance. The product maintainers might provide some support
    for these features as a best effort only.
  properties:
    namespace:
      default: openshift-netobserv
