apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# Adds namespace to all resources.
namespace: netobserv

# Value of this field is prepended to the
# names of all resources, e.g. a deployment named
# "wordpress" becomes "alices-wordpress".
# Note that it should also match with the prefix (text before '-') of the namespace
# field above.
namePrefix: netobserv-

resources:
- monitor.yaml
- ../crd
- ../rbac
- ../manager
- ../webhook
- namespace.yaml

patches:
- path: ./monitoring-patch.yaml
  target:
    kind: Deployment
    name: controller-manager
- path: patch.yaml
