#flp_confgen
description:
  This metric observes the nodes incoming traffic
details:
  Sum bytes for incoming traffic per source and destination nodes
usage:
  Evaluate network incoming usage breakdown per source and destination nodes
tags:
  - ingress
  - bytes
  - nodes
encode:
  type: prom
  prom:
    metrics:
      - name: node_ingress_bytes_total
        type: counter
        valuekey: Bytes
        filters:
        - key: FlowDirection
          value: "0|2"
        - key: Duplicate
          value: "false"
        labels:
          - SrcK8S_HostName
          - DstK8S_HostName
