#flp_confgen
description:
  This metric observes the incoming traffic
details:
  Sum bytes for incoming traffic per source and destination namespaces and owners
usage:
  Evaluate network incoming usage breakdown per source and destination namespaces and owners
tags:
  - ingress
  - bytes
  - workloads
encode:
  type: prom
  prom:
    metrics:
      - name: workload_ingress_bytes_total
        type: counter
        valuekey: Bytes
        filters:
        - key: FlowDirection
          value: "0|2"
        - key: Duplicate
          value: "false"
        labels:
          - SrcK8S_Namespace
          - DstK8S_Namespace
          - SrcK8S_OwnerName
          - DstK8S_OwnerName
          - SrcK8S_OwnerType
          - DstK8S_OwnerType
