apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  name: release-netobserv-1-8-1-2
  namespace: ocp-network-observab-tenant
  labels:
    release.appstudio.openshift.io/author: 'jtakvori'
spec:
  releasePlan: netobserv-zstream
  snapshot: netobserv-zstream-pxhn8
  data:
    releaseNotes:
      type: RHSA
      cves:
        - key: CVE-2024-56171
          component: network-observability-operator-zstream
        - key: CVE-2025-24928
          component: network-observability-operator-zstream
      references: # note: these links were ignored during the release because RPA links take precedence; anyway, there's a link to the doc release note, which can be sufficient.
        - https://issues.redhat.com/browse/NETOBSERV-2218
        - https://issues.redhat.com/browse/NETOBSERV-2139
