{
 "title": "NetObserv Metrics",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "_node",
    "label": "Node",
    "query": "label_values(kubelet_node_name, node)"
   }
  ]
 },
 "panels": [
  {
   "title": "NetObserv Pod CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pod:container_cpu_usage:sum{namespace=\"network-observability\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "NetoBserv Pod Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"network-observability\",container=\"\", node=~\"$_node\"}) by (container, pod, namespace, node )",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "loki-store PVC Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(kubelet_volume_stats_used_bytes{namespace=\"network-observability\", persistentvolumeclaim=\"loki-store\"}[5m])",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "Flows processed per minute",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(flow_process_nf_count[1m])*60) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Number of Packets Processed Per minute",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(flow_traffic_packets[1m])*60) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Flow Process Error count per minute",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(flow_process_nf_errors_count[1m])*60) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Number of bytes for flows per minute",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(flow_traffic_summary_size_bytes_sum[1m])*60) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Flow Processing time 90% quantile",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "flow_summary_processing_time_us{quantile=\"0.9\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}