apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/netobserv/network-observability-operator?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "push" && target_branch
      == "main" &&
      (".tekton/***".pathChanged() ||
      "catalog.Dockerfile.downstream".pathChanged() ||
      "catalog/***".pathChanged() ||
      "hack/update-build.sh".pathChanged() ||
      "hack/bundle_digest.sh".pathChanged() ||
      "hack/patch_catalog.py".pathChanged() ||
      "hack/patch_csv.py".pathChanged())
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: fbc-v4-17
    appstudio.openshift.io/component: fbc-v4-17
    pipelines.appstudio.openshift.io/type: build
  name: fbc-v4-17-on-push
  namespace: ocp-network-observab-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/redhat-user-workloads/ocp-network-observab-tenant/fbc-v4-17:latest
  - name: build-platforms
    value:
    - linux/x86_64
  - name: dockerfile
    value: catalog.Dockerfile.downstream
  - name: opm-image
    value: registry.redhat.io/openshift4/ose-operator-registry-rhel9:v4.17
  pipelineRef:
    name: build-fbc-pipeline
  workspaces:
  - name: workspace
    volumeClaimTemplate:
      metadata:
        creationTimestamp: null
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
      status: {}
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}
