apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/netobserv/network-observability-operator?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "pull_request" && target_branch
      == "release-1.8"  &&
      (".tekton/***".pathChanged() ||
      "bundle.Dockerfile.downstream".pathChanged() ||
      "bundle/***".pathChanged() ||
      "./requirements.txt".pathChanged() ||
      "hack/update-build.sh".pathChanged() ||
      "hack/patch_csv.py".pathChanged())
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: netobserv-operator-1-8
    appstudio.openshift.io/component: network-observability-operator-bundle-1-8
    pipelines.appstudio.openshift.io/type: build
  name: network-observability-operator-bundle-1-8-on-pull-request
  namespace: ocp-network-observab-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/redhat-user-workloads/ocp-network-observab-tenant/netobserv-operator/network-observability-operator-bundle:on-pr-{{revision}}
  - name: image-expires-after
    value: 5d
  - name: dockerfile
    value: bundle.Dockerfile.downstream
  - name: prefetch-input
    value: "{\"type\":\"pip\", \"path\":\".\"}"
  pipelineRef:
    name: build-bundle-pipeline
  workspaces:
  - name: workspace
    volumeClaimTemplate:
      metadata:
        creationTimestamp: null
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
      status: {}
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
