apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/netobserv/network-observability-operator?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "pull_request" && target_branch
      == "main" && (".tekton/***".pathChanged() || "apis/***".pathChanged() || "controllers/***".pathChanged()
      || "Dockerfile.downstream".pathChanged() || "docs/***".pathChanged() || "hack/update-build.sh".pathChanged()
      || "LICENSE".pathChanged() || "main.go".pathChanged() || "Makefile".pathChanged()
      || "manifests/***".pathChanged() || "pkg/***".pathChanged())
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: netobserv-ystream
    appstudio.openshift.io/component: network-observability-operator-ystream
    pipelines.appstudio.openshift.io/type: build
  name: network-observability-operator-ystream-on-pull-request
  namespace: ocp-network-observab-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/redhat-user-workloads/ocp-network-observab-tenant/network-observability-operator-ystream:on-pr-{{revision}}
  - name: image-expires-after
    value: 5d
  - name: build-args-file
    value: Dockerfile-args.downstream
  - name: dockerfile
    value: ./Dockerfile.downstream
  - name: build-platforms
    value:
    - linux/x86_64
  pipelineRef:
    name: build-pipeline
  taskRunTemplate:
    serviceAccountName: build-pipeline-network-observability-operator-ystream
status: {}
