apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/netobserv/network-observability-operator?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    # switch comment in/out at branch cut
    # pipelinesascode.tekton.dev/on-cel-expression: |
    #   event == "push" && target_branch == "main" && (
    #     ".tekton/***".pathChanged() ||
    #     ".dockerignore".pathChanged() ||
    #     "bundle.Dockerfile.downstream".pathChanged() ||
    #     "bundle/***".pathChanged() ||
    #     "requirements.txt".pathChanged() ||
    #     "hack/update-build.sh".pathChanged() ||
    #     "hack/nudging/container_digest.sh".pathChanged() ||
    #     "hack/patch_csv.py".pathChanged()
    #   )
    pipelinesascode.tekton.dev/on-cel-expression: "false"
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: netobserv-ystream
    appstudio.openshift.io/component: network-observability-operator-bundle-ystream
    pipelines.appstudio.openshift.io/type: build
  name: network-observability-operator-bundle-ystream-on-push
  namespace: ocp-network-observab-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/redhat-user-workloads/ocp-network-observab-tenant/network-observability-operator-bundle-ystream:latest
  - name: build-args-file
    value: Dockerfile-args.downstream
  - name: dockerfile
    value: bundle.Dockerfile.downstream
  - name: prefetch-input
    value: '{"type":"pip", "path":"."}'
  pipelineRef:
    name: build-bundle-pipeline
  taskRunTemplate:
    serviceAccountName: build-pipeline-network-observability-operator-bundle-ystream
  workspaces:
  - name: workspace
    volumeClaimTemplate:
      metadata:
        creationTimestamp: null
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
      status: {}
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}
