apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  name: netobserv-flowcollector-viewer-plugin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: netobserv-flowcollector-viewer-role
subjects:
- kind: ServiceAccount
  name: netobserv-plugin
  namespace: netobserv
