name: Push PR image to quay.io
on:
  workflow_run:
    workflows: ["Build PR image and upload artifact"]
    types:
      - completed

env:
  WF_REGISTRY_USER: netobserv+github_ci

jobs:
  push-pr-image:
    if: >
      github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success'
    name: push PR image
    runs-on: ubuntu-latest
    steps:
      - name: download artifact
        uses: actions/download-artifact@v5
        with:
          name: pr
          run-id: ${{github.event.workflow_run.id }}
          github-token: ${{secrets.GITHUB_TOKEN}}
      - name: load images
        run: |
          docker load --input ./operator.tar
          docker load --input ./bundle.tar
      - name: docker login to quay.io
        uses: docker/login-action@v2
        with:
          username: ${{ env.WF_REGISTRY_USER }}
          password: ${{ secrets.QUAY_SECRET }}
          registry: quay.io
      - name: push operator and bundle
        run: |
          DOCKER_BUILDKIT=1 docker push $(cat ./operator-name)
          DOCKER_BUILDKIT=1 docker push $(cat ./bundle-name)
      - name: build and push catalog
        run: |
          IMAGE_ORG=${{ env.WF_ORG }} BUNDLE_VERSION=0.0.0-sha-$(cat ./short-sha) make shortlived-catalog-build catalog-push
      - uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            var fs = require('fs');
            var issueNumber = Number(fs.readFileSync('./pr-id'));
            var shortSha = String(fs.readFileSync('./short-sha')).trim();
            var operatorImage = fs.readFileSync('./operator-name');
            var bundleImage = fs.readFileSync('./bundle-name');
            github.rest.issues.createComment({
              issue_number: issueNumber,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `New images:
            \`\`\`bash
            ${operatorImage}
            ${bundleImage}
            quay.io/netobserv/network-observability-operator-catalog:v0.0.0-sha-${shortSha}
            \`\`\`

            They will expire in two weeks.

            To deploy this build:
            \`\`\`bash
            # Direct deployment, from operator repo
            IMAGE=${operatorImage} make deploy

            # Or using operator-sdk
            operator-sdk run bundle ${bundleImage}
            \`\`\`

            Or as a Catalog Source:
            \`\`\`yaml
            apiVersion: operators.coreos.com/v1alpha1
            kind: CatalogSource
            metadata:
              name: netobserv-dev
              namespace: openshift-marketplace
            spec:
              sourceType: grpc
              image: quay.io/netobserv/network-observability-operator-catalog:v0.0.0-sha-${shortSha}
              displayName: NetObserv development catalog
              publisher: Me
              updateStrategy:
                registryPoll:
                  interval: 1m
            \`\`\`
            `
            })
