name: Push PR image to quay.io
on:
  workflow_run:
    workflows: ["Build PR image and upload artifact"]
    types:
      - completed

permissions: {}

env:
  WF_REGISTRY_USER: netobserv+operator_github_ci
  WF_REGISTRY: quay.io/netobserv
  WF_IMAGE: network-observability-operator

jobs:
  extract-data:
    permissions:
      pull-requests: read
    if: >
      github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success'
    name: extract and validate PR data
    runs-on: ubuntu-latest
    outputs:
      pr_id: ${{ steps.extract.outputs.pr_id }}
      main_image: ${{ steps.extract.outputs.main_image }}
      bundle_image: ${{ steps.extract.outputs.bundle_image }}
      catalog_image: ${{ steps.extract.outputs.catalog_image }}
    steps:
      - name: extract PR data
        id: extract
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AUTHOR: ${{ github.event.workflow_run.head_repository.owner.login }}
          BRANCH: ${{ github.event.workflow_run.head_branch }}
        run: |
          pr_json=$(gh api --method GET "repos/$GITHUB_REPOSITORY/pulls" -f state=open -f "head=$AUTHOR:$BRANCH")
          len=$(echo ${pr_json} | jq '. | length')
          if [[ "$len" != "1" ]]; then
            echo "::error::Could not get a unique PR, aborting"
            exit 1
          fi
          has_label=$(echo ${pr_json} | jq '[.[0].labels[].name] | any(. == "ok-to-test")')
          if [[ "$has_label" != "true" ]]; then
            echo "::error::PR does not have the ok-to-test label, aborting"
            exit 1
          fi
          head_sha=$(echo ${pr_json} | jq -r '.[0].head.sha')
          echo "pr_id=$(echo ${pr_json} | jq '.[0].number')" >> $GITHUB_OUTPUT
          echo "main_image=${WF_REGISTRY}/${WF_IMAGE}:${head_sha::8}" >> $GITHUB_OUTPUT
          echo "bundle_image=${WF_REGISTRY}/${WF_IMAGE}-bundle:v0.0.0-sha-${head_sha::8}" >> $GITHUB_OUTPUT
          echo "catalog_image=${WF_REGISTRY}/${WF_IMAGE}-catalog:v0.0.0-sha-${head_sha::8}" >> $GITHUB_OUTPUT
  push:
    needs: extract-data
    name: push PR image
    runs-on: ubuntu-latest
    steps:
      - name: download artifact
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8
        with:
          name: pr
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: load images
        run: |
          docker load --input ./operator.tar
          docker load --input ./bundle.tar
          docker load --input ./catalog.tar
      - name: docker login to quay.io
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4.6.0
        with:
          username: ${{ env.WF_REGISTRY_USER }}
          password: ${{ secrets.QUAY_SECRET }}
          registry: quay.io
      - name: push operator, bundle and catalog
        env:
          MAIN_IMAGE: ${{ needs.extract-data.outputs.main_image }}
          BUNDLE_IMAGE: ${{ needs.extract-data.outputs.bundle_image }}
          CATALOG_IMAGE: ${{ needs.extract-data.outputs.catalog_image }}
        run: |
          DOCKER_BUILDKIT=1 docker push "$MAIN_IMAGE"
          DOCKER_BUILDKIT=1 docker push "$BUNDLE_IMAGE"
          DOCKER_BUILDKIT=1 docker push "$CATALOG_IMAGE"
  comment:
    permissions:
      pull-requests: write
    needs: [extract-data, push]
    name: comment on PR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9
        env:
          MAIN_IMAGE: ${{ needs.extract-data.outputs.main_image }}
          BUNDLE_IMAGE: ${{ needs.extract-data.outputs.bundle_image }}
          CATALOG_IMAGE: ${{ needs.extract-data.outputs.catalog_image }}
          PR_ID: ${{ needs.extract-data.outputs.pr_id }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const mainImage = process.env.MAIN_IMAGE;
            const bundleImage = process.env.BUNDLE_IMAGE;
            const catalogImage = process.env.CATALOG_IMAGE;
            github.rest.issues.createComment({
              issue_number: parseInt(process.env.PR_ID, 10),
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `New images:
            \`\`\`bash
            ${mainImage}
            ${bundleImage}
            ${catalogImage}
            \`\`\`

            They will expire in two weeks.

            To deploy this build:
            \`\`\`bash
            # Direct deployment, from operator repo
            IMAGE=${mainImage} make deploy

            # Or using operator-sdk
            operator-sdk run bundle ${bundleImage}
            \`\`\`

            Or as a Catalog Source:
            \`\`\`yaml
            apiVersion: operators.coreos.com/v1alpha1
            kind: CatalogSource
            metadata:
              name: netobserv-dev
              namespace: openshift-marketplace
            spec:
              sourceType: grpc
              image: ${catalogImage}
              displayName: NetObserv development catalog
              publisher: Me
              updateStrategy:
                registryPoll:
                  interval: 1m
            \`\`\`
            `
            })
