name: Remove ok-to-test
on:
  pull_request_target:
    types: [synchronize,reopened]

permissions:
  pull-requests: write

jobs:
  rm-ok-to-test:
    if: contains(github.event.pull_request.labels.*.name, 'ok-to-test')
    runs-on: ubuntu-latest
    name: Remove ok-to-test
    steps:
      - uses: actions-ecosystem/action-remove-labels@2ce5d41b4b6aa8503e285553f75ed56e0a40bae0 # v1.3.0
        with:
          labels: ok-to-test
          fail_on_error: true
